"""Signs added in 0.1.0.

Each one reports a fact established by a local, deterministic check -- no
network, no model, no heuristic scoring. Every sign here was selected against
a documented failure report rather than invented; the evidence for each is
cited in its docstring so a reader can judge whether the sign earns its place.

Signs that only matter when content is about to change fire on write-shaped
tools only. Firing them on a read would be true but useless, and a true-but-
useless sign is how a tool like this gets muted.
"""

from __future__ import annotations

import functools
import os
import re
from typing import List, Optional

from . import gitfacts, state
from .signs import VENDORED_RE, Context, Sign, register

# Tools that change file content. Read is deliberately excluded from signs
# whose entire consequence is "what you are about to write will go wrong".
WRITE_TOOLS = {"Edit", "Write", "NotebookEdit", "MultiEdit", "create_file", "str_replace_editor"}

# Bytes sampled from the head of a file for content-based checks. Bounded so a
# multi-gigabyte file cannot stall the hot path.
SAMPLE_BYTES = 8192

CONFLICT_RE = re.compile(rb"^(<{7}|={7}|>{7})(\s|$)", re.MULTILINE)
GENERATED_RE = re.compile(
    rb"(@generated|Code generated by|DO NOT EDIT|AUTO-GENERATED|autogenerated by)",
    re.IGNORECASE,
)


def _is_write(ctx: Context) -> bool:
    return ctx.tool_name in WRITE_TOOLS


@functools.lru_cache(maxsize=32)
def _sample(path: str, nbytes: int = SAMPLE_BYTES) -> Optional[bytes]:
    try:
        with open(path, "rb") as fh:
            return fh.read(nbytes)
    except (OSError, ValueError):
        return None


def _repo_for(ctx: Context) -> Optional[str]:
    if VENDORED_RE.search(ctx.target_path):
        return None
    return gitfacts.repo_root(ctx.target_path)


def _emit(ctx: Context, sign_id: str, repo: str, token: str, text: str) -> Optional[Sign]:
    """Apply the shared ack + once-per-session policy, then hand back the sign."""
    if state.is_acknowledged(repo, sign_id, token):
        return None
    if state.already_signed(ctx.session_id, repo + "|" + ctx.target_path, sign_id):
        return None
    return Sign(id=sign_id, text=text, state_token=token, repo=repo + "|" + ctx.target_path)


# ---------------------------------------------------------------- symlink escape

@register
def symlink_escape(ctx: Context) -> Optional[Sign]:
    """The path resolves, through a symlink, to somewhere outside the repository.

    Evidence: the "GhostApproval" trust-boundary research (Wiz, reported Q1 2026,
    detailed July 2026) showed a symlink committed inside an ordinary-looking
    repository file causing AI coding assistants to read and write outside the
    workspace -- demonstrated across several vendors, including overwriting
    ~/.ssh/authorized_keys. Anthropic shipped a symlink warning in Claude Code
    2.1.32 in response.

    This reports only the boundary crossing. It makes no claim about intent: a
    symlink out of a repo is often deliberate, which is why the text says where
    the path actually lands rather than calling it an attack.
    """
    root = _repo_for(ctx)
    if root is None:
        return None

    target = ctx.target_path
    try:
        real = os.path.realpath(target)
    except (OSError, ValueError):
        return None

    # No symlink component means no boundary to cross.
    if os.path.abspath(target) == real:
        return None

    real_root = os.path.realpath(root)
    if real == real_root or real.startswith(real_root + os.sep):
        return None  # resolves back inside the same repo, common in monorepos

    token = "symlink:%s->%s" % (os.path.abspath(target), real)
    text = (
        "SYMLINK LEAVES REPO - {shown} resolves to {real}, which is outside {name}. "
        "Anything written here lands outside the repository and will not appear in its "
        "diff. Confirm this indirection is intended. Inspect: ls -l {shown}"
    ).format(shown=target, real=real, name=os.path.basename(real_root))
    return _emit(ctx, "symlink_escape", root, token, text)


# ------------------------------------------------------------- conflict markers

@register
def conflict_markers(ctx: Context) -> Optional[Sign]:
    """The file currently on disk contains unresolved merge-conflict markers.

    Evidence: "AgenticFlict" (arXiv 2604.03551) analysed 142k+ AI-agent-authored
    pull requests across 59k+ repositories and found a 27.67% conflict rate. A
    concrete instance -- conflict markers merged into a README and passing CI
    unnoticed -- is SecPal/frontend#113, whose fix was to add a git grep
    preflight for exactly this.

    Fires on reads too: an agent reasoning over a conflicted file without
    registering the markers is the failure, not just writing one.
    """
    root = _repo_for(ctx)
    if root is None:
        return None
    if not os.path.isfile(ctx.target_path):
        return None

    blob = _sample(ctx.target_path)
    if not blob:
        return None
    hits = CONFLICT_RE.findall(blob)
    if not hits:
        return None

    token = "conflict:%s:%d" % (ctx.target_path, len(hits))
    text = (
        "UNRESOLVED CONFLICT - {name} still contains git conflict markers "
        "(<<<<<<< / ======= / >>>>>>>) in the first {n}KB. Editing or reasoning over it in "
        "this state will treat both sides of the conflict as real content. "
        "Inspect: git -C {root} diff --check -- {path}"
    ).format(
        name=os.path.basename(ctx.target_path),
        n=SAMPLE_BYTES // 1024,
        root=root,
        path=ctx.target_path,
    )
    return _emit(ctx, "conflict_markers", root, token, text)


# --------------------------------------------------------- concurrent worktree

@register
def concurrent_worktree_edit(ctx: Context) -> Optional[Sign]:
    """Another worktree of this repo has uncommitted changes to this same file.

    Evidence: the documented 2026 parallel-agent failure -- "within about ninety
    seconds, two agents were overwriting each other's edits to the same file,
    neither one aware the other existed." Running several agents over one
    repository via git worktrees is now common practice, and the collisions are
    silent.

    Write-shaped tools only: a read racing another worktree's edit is not itself
    unsafe.
    """
    if not _is_write(ctx):
        return None
    root = _repo_for(ctx)
    if root is None:
        return None

    listing = gitfacts._git(root, "worktree", "list", "--porcelain")
    if not listing:
        return None

    others: List[str] = []
    for line in listing.splitlines():
        if line.startswith("worktree "):
            wt = line[len("worktree "):].strip()
            if wt and os.path.realpath(wt) != os.path.realpath(root):
                others.append(wt)
    if not others:
        return None

    try:
        rel = os.path.relpath(os.path.realpath(ctx.target_path), os.path.realpath(root))
    except ValueError:
        return None
    if rel.startswith(".."):
        return None

    dirty: List[str] = []
    for wt in others:
        sibling = os.path.join(wt, rel)
        if not os.path.exists(sibling):
            continue
        st = gitfacts._git(wt, "status", "--porcelain", "--", rel)
        if st:
            dirty.append(wt)
    if not dirty:
        return None

    token = "worktree:%s:%s" % (rel, "|".join(sorted(dirty)))
    text = (
        "CONCURRENT EDIT - {n} other worktree(s) of this repository have uncommitted changes "
        "to {rel}: {where}. If another agent is working there, one of these edits will be "
        "silently lost. Inspect: git -C {first} status --porcelain -- {rel}"
    ).format(n=len(dirty), rel=rel, where=", ".join(dirty), first=dirty[0])
    return _emit(ctx, "concurrent_worktree_edit", root, token, text)


# ------------------------------------------------------------------ binary edit

@register
def binary_edit(ctx: Context) -> Optional[Sign]:
    """A binary file is about to be edited as if it were text.

    Evidence: google-gemini/gemini-cli#2441, "Gemini CLI Creating Corrupted Files
    with Binary Data and Invisible Characters", and reports of binary assets
    becoming unusable once committed. Detection uses the same NUL-byte test git
    itself uses to classify a file as binary.
    """
    if not _is_write(ctx):
        return None
    root = _repo_for(ctx)
    if root is None:
        return None
    if not os.path.isfile(ctx.target_path):
        return None

    blob = _sample(ctx.target_path)
    if not blob or b"\x00" not in blob:
        return None

    token = "binary:%s:%d" % (ctx.target_path, os.path.getsize(ctx.target_path))
    text = (
        "BINARY FILE - {name} contains NUL bytes, the same test git uses to classify a file "
        "as binary. A text-shaped edit will corrupt it, and the damage usually surfaces only "
        "after it is committed. Inspect: file {path}"
    ).format(name=os.path.basename(ctx.target_path), path=ctx.target_path)
    return _emit(ctx, "binary_edit", root, token, text)


# --------------------------------------------------------------- generated file

@register
def generated_file(ctx: Context) -> Optional[Sign]:
    """The file declares itself machine-generated.

    The marker conventions are long-established across protoc, mockgen, sqlc,
    wire, terraform and graphql-codegen. Note honestly: unlike the other signs
    here, this one rests on the ubiquity of the convention plus the general
    documented pattern of agents rewriting whole files, rather than on a single
    named incident. Soundness is not in question -- it is a literal string match
    on the file's own header -- but the evidence for its importance is weaker.
    """
    if not _is_write(ctx):
        return None
    root = _repo_for(ctx)
    if root is None:
        return None
    if not os.path.isfile(ctx.target_path):
        return None

    head = _sample(ctx.target_path, 2048)
    if not head:
        return None
    first_lines = b"\n".join(head.split(b"\n")[:5])
    m = GENERATED_RE.search(first_lines)
    if not m:
        return None

    token = "generated:%s" % ctx.target_path
    text = (
        'GENERATED FILE - {name} declares itself machine-generated ("{marker}") in its '
        "header. Edits here are overwritten the next time the generator runs; the source of "
        "truth is whatever produces it. Inspect: head -5 {path}"
    ).format(
        name=os.path.basename(ctx.target_path),
        marker=m.group(0).decode("utf-8", "replace"),
        path=ctx.target_path,
    )
    return _emit(ctx, "generated_file", root, token, text)


def clear_caches() -> None:
    """Drop cached file samples. Call once per evaluation."""
    _sample.cache_clear()
